# Generated by Django 4.2.5 on 2023-11-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='value',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
