# Generated by Django 4.2.5 on 2023-11-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_stock_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=30)),
                ('qty', models.FloatField()),
                ('sum', models.FloatField()),
                ('note', models.CharField(max_length=200)),
            ],
        ),
    ]
