# Generated by Django 4.2.5 on 2023-12-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_saving'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='qty',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='qty',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='sum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
