# Generated by Django 4.2.5 on 2023-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_stockmarket_stock_note_stock_qty_stock_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField(null=True)),
                ('qty', models.FloatField(null=True)),
                ('sum', models.FloatField(null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
