# Generated by Django 4.2.5 on 2023-12-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_stock_saving_name_saving_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField(null=True)),
                ('qty', models.FloatField(null=True)),
                ('sum', models.FloatField(null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.FloatField(null=True)),
                ('qty', models.FloatField(null=True)),
                ('sum', models.FloatField(null=True)),
                ('note', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
