# Generated by Django 4.2.5 on 2024-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_choices_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=50, null=True)),
                ('name2', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
